- name: Install standard packages
  ansible.builtin.apt:
    name:
      - curl
      - dnsutils
      - kitty-terminfo
    update_cache: yes

- name: Configure timezone
  community.general.timezone:
    name: Asia/Jakarta

- name: Add HashiCorp GPG key
  ansible.builtin.get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /etc/apt/trusted.gpg.d/hashicorp.asc

- name: Configure HashiCorp repository
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/trusted.gpg.d/hashicorp.asc] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main

- name: Install Nomad
  ansible.builtin.apt:
    name:
      - nomad
    update_cache: yes
